# Generated by Django 6.0.1 on 2026-01-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labsettings',
            name='areas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labsettings',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='labsettings',
            name='highlights',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labsettings',
            name='lead',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='labsettings',
            name='partners',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labsettings',
            name='team',
            field=models.TextField(blank=True, null=True),
        ),
    ]
