# Generated by Django 6.0.1 on 2026-01-31 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_labsettings_areas_labsettings_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0)),
                ('lab_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_images', to='core.labsettings')),
            ],
            options={
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
