# Generated by Django 6.0.1 on 2026-01-31 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_labsettings_country_labsettings_neighborhood_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labsettings',
            name='city',
        ),
        migrations.RemoveField(
            model_name='labsettings',
            name='country',
        ),
        migrations.RemoveField(
            model_name='labsettings',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='labsettings',
            name='number',
        ),
        migrations.RemoveField(
            model_name='labsettings',
            name='state',
        ),
        migrations.RemoveField(
            model_name='labsettings',
            name='street',
        ),
        migrations.RemoveField(
            model_name='labsettings',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='labsettings',
            name='address_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labsettings',
            name='maps_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
