# Generated by Django 4.2 on 2026-02-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_equipment_assigned_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="members_order",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
