# Generated by Django 6.0.2 on 2026-06-10 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_bilingual_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='researcharea',
            name='link',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
