# Generated by Django 4.2.20 on 2025-05-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('professor', 'Professor'), ('student', 'Student'), ('colaborator', 'Collaborator')], default='colaborator', max_length=50),
        ),
    ]
