# Generated by Django 6.0.1 on 2026-01-31 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='researcher_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='show_in_researchers',
            field=models.BooleanField(default=True),
        ),
    ]
