# Generated by Django 4.2.20 on 2025-05-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_date_of_birth_user_birthdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('professor', 'Professor'), ('student', 'Student'), ('collaborator', 'Collaborator')], default='collaborator', max_length=50),
        ),
    ]
