# Generated by Django 6.0.2 on 2026-06-09 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_bilingual_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='language',
            field=models.CharField(choices=[('pt', 'Português'), ('en', 'English')], default='pt', max_length=5),
        ),
    ]
